server:
  port: ${PORT:0}

spring:
  application:
    name: order-service
    instance:
      instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
      h2:
        console:
          enabled: true
          path: /h2-console
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka